<a href="https://colab.research.google.com/github/AlpacaJake/AI-python-connect/blob/master/Pytorch_logistic_regression.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import torch
import torch.nn as nn
import torch.nn.functional as F
import torch.optim as optim

In [2]:
torch.manual_seed(1)

In [3]:
x_data = [[1,2], [2,3], [3,1], [4,3], [5,3],[6,2]]
y_data = [[0], [0], [0], [1], [1], [1]]

x_train = torch.FloatTensor(x_data)
y_train = torch.FloatTensor(y_data)


In [4]:
print(x_train.shape)
print(y_train.shape)

torch.Size([6, 2])
torch.Size([6, 1])


In [5]:
print('e^1 equals: ', torch.exp(torch.FloatTensor([1])))

e^1 equals:  tensor([2.7183])


In [6]:
W = torch.zeros((2,1), requires_grad=True)
b = torch.zeros(1, requires_grad=True)


In [11]:
#hypothesis = 1 / (1 + torch.exp(-(x_train.matmul(W) + b)))
hypothesis = torch.sigmoid(x_train.matmul(W)+b)


In [12]:
print(hypothesis)
print(hypothesis.shape)

tensor([[0.5000],
        [0.5000],
        [0.5000],
        [0.5000],
        [0.5000],
        [0.5000]], grad_fn=<SigmoidBackward>)
torch.Size([6, 1])


In [10]:
print('1 / (1 + e^(-1)) equals: ', torch.sigmoid(torch.FloatTensor([1])))


1 / (1 + e^(-1)) equals:  tensor([0.7311])


In [13]:
#losses = -(y_train * torch.log(hypothesis) + (1 - y_train) * torch.log(1 - hypothesis))
#print(losses)

tensor([[0.6931],
        [0.6931],
        [0.6931],
        [0.6931],
        [0.6931],
        [0.6931]], grad_fn=<NegBackward>)


In [15]:
#cost = losses.mean()
#cost = F.binary_cross_entropy(hypothesis, y_train)
#print(cost)

tensor(0.6931, grad_fn=<BinaryCrossEntropyBackward>)


In [16]:
optimizer = optim.SGD([W, b], lr = 0.1)

In [21]:
nb_epochs = 10000

for epoch in range(nb_epochs + 1) :

  hypothesis = torch.sigmoid(x_train.matmul(W)+b)
  cost = F.binary_cross_entropy(hypothesis, y_train)

  optimizer.zero_grad()
  cost.backward()
  optimizer.step()

  if epoch % 1000 == 0:
    print('Epoch {:4d}/{} Cost: {:.6f}'.format(epoch, nb_epochs, cost.item()))

print(W)
print(b)

Epoch    0/10000 Cost: 0.081456
Epoch 1000/10000 Cost: 0.058336
Epoch 2000/10000 Cost: 0.045575
Epoch 3000/10000 Cost: 0.037451
Epoch 4000/10000 Cost: 0.031813
Epoch 5000/10000 Cost: 0.027664
Epoch 6000/10000 Cost: 0.024480
Epoch 7000/10000 Cost: 0.021959
Epoch 8000/10000 Cost: 0.019911
Epoch 9000/10000 Cost: 0.018214
Epoch 10000/10000 Cost: 0.016785
tensor([[3.4157],
        [1.6050]], requires_grad=True)
tensor([-15.2316], requires_grad=True)


In [24]:
#evaluation
x_test = torch.FloatTensor([[1,3], [2,5], [3,1], [5,3], [6,2]])

hypothesis = torch.sigmoid(x_test.matmul(W)+ b)

prediction = hypothesis >= torch.FloatTensor([0.5])
print(prediction[:5].float())

tensor([[0.],
        [0.],
        [0.],
        [1.],
        [1.]])
